langfuse/callback.py

Added `anthropic-chat` as possible llm type returned by Anthropic to fix error with tracing Anthropic LLM generations. The error comes from the type returned by Anthropic to have changed to `anthropic-chat`.
```
Traceback (most recent call last):
File "/Users/ruben/git/rag-chatbot-lambda/venv_3.11/lib/python3.11/site-packages/langfuse/callback.py", line 445, in __on_llm_action
model_name = kwargs["invocation_params"]["model_name"]
~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'model_name'
```

Added anthropic-chat as possible llm type returned by Anthropic 

---

langfuse/api/resources/commons/types/trace.py
langfuse/api/resources/trace/types/create_trace_request.py

Contributes to https://github.com/langfuse/langfuse/issues/625

feat: publish trace

---

.github/workflows/ci.yml
README.md
langfuse/callback.py
poetry.lock
pyproject.toml
tests/test_core_sdk.py
tests/test_datasets.py
tests/test_logger.py
tests/test_sdk_setup.py

* moved langchain to dev dependencies
* added try-catch block to avoid import errors for users who don't have langchain installed
* added poetry extra so that people can install langchain with langfuse, should they wish to
Hi! Upon installing the SDK, I noticed it depends on langchain, which in turn brings:
```
$ poetry show langchain
name         : langchain                                             
version      : 0.0.346                                               
description  : Building applications with LLMs through composability 
dependencies
- aiohttp >=3.8.3,<4.0.0
- anyio <4.0
- async-timeout >=4.0.0,<5.0.0
- dataclasses-json >=0.5.7,<0.7
- jsonpatch >=1.33,<2.0
- langchain-core >=0.0.10,<0.1
- langsmith >=0.0.63,<0.1.0
- numpy >=1,<2
- pydantic >=1,<3
- PyYAML >=5.3
- …
```

Make langchain optional

---

langfuse/client.py
langfuse/request.py
tests/test_sdk_setup.py

`session` can be ambiguous because it is used in the Langfuse domain.
Related to #329

chore: rename client to httpx_client

---

langfuse/openai.py
tests/test_core_sdk.py
tests/test_openai.py

…ations, spans and events (#289)

feat: support `user_id` argument for OpenAI Chat completions

---

langfuse/serializer.py
tests/test_json.py

Fixes https://github.com/langfuse/langfuse/issues/948
For my case, it was a dataclass which I was returning as a chain output, and python default JSON serializer does not support dataclasses dumping.. See [StackOverflow Thread](https://stackoverflow.com/questions/51286748/make-the-python-json-encoder-support-pythons-new-dataclasses).
So, I have fixed that as per answer in the thread.
But, there are many more cases where it might fail later also.. So, I checked how LangSmith folks have done.. Here is the [source](https://github.com/langchain-ai/langsmith-sdk/blob/6ff1369f7c226e79782fbe51106d67fbe466218f/python/langsmith/client.py#L158).. Maybe we can take some more inspirations from there, and make the serializer more robust here...

fix: support more types for JSON serialization

---

langfuse/openai.py
tests/test_openai.py

Implements https://github.com/langfuse/langfuse/issues/1092

feat(openai-python): support for parent_observation_id to nest generations created by the integration

---

langfuse/client.py
tests/test_core_sdk.py

Non breaking, coalesce to sessionId if no session_id

fix: session_id instead of sessionId on trace methods

---

langfuse/callback/langchain.py

Correctly handle tool/function messages returned by Agent/Tool
Error example:
```
ERROR:langfuse:Got unknown type <class 'langchain_core.messages.tool.ToolMessage'>: content="..." additional_kwargs={'name': '...'} tool_call_id='call_b7LCGSeZNzcZZBoLJ6emDaio'
Traceback (most recent call last):
File "/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 369, in on_chat_model_start
[self._create_message_dicts(m) for m in messages]
File "/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-packages/langfuse/callback/langchain.py", line 369, in <listcomp>
[self._create_message_dicts(m) for m in messages]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Caskroom/miniconda/base/envs/py3.11/lib/python3.11/site-package …
```

langchain.callback supports ToolMessage, FunctionMessage

---

.github/workflows/availability-partner-packages.yml
.github/workflows/package-availability-check.yml

Adding ci workflow to test availability of packages, especially as partners might change how they deploy our integrations

ci: check availability of packages

---

langfuse/llama_index/llama_index.py

Adds handling for Embeddings and chunks in Trace IO. Removes full logging of both embeddings and chunks to only show counts.

fix: remove full embedding and chunk logs from traces

---

langfuse/model.py
tests/test_prompt.py
tests/test_prompt_compilation.py

- Allow `content` as prompt var again
- If variable is set to `None` replace with empty string "" instead of "None"

fix: allow 'content' as prompt var

---

langfuse/openai.py

Tighten checks for `model` existence to return null if `model` is an empty string via check for truthiness.

fix: do not overwrite model if openai response has empty string as model

---

langfuse/callback/langchain.py

`meta` can be `None`, see https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback/langchain.py#L722, but `meta.update()` at https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback/langchain.py#L445 would fail on `None`
This fixes bug report https://github.com/langfuse/langfuse-python/issues/599

Bugfix: to fix issue #599 where `meta` can be `None`

---

langfuse/callback/langchain.py

Bugfix: to fix issue #1775 where `meta` can be `None`
`meta` can be `None`, see https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback/langchain.py#L722, but `meta.update()` at https://github.com/langfuse/langfuse-python/blob/main/langfuse/callback/langchain.py#L445 would fail on `None`

fix: issue #599 where `meta` can be `None` (#598)

---

langfuse/callback/langchain.py

Add handling of corner case where `last_response.text` can be empty - in case of vertex AI LLMs.
Solves this issue: https://github.com/langfuse/langfuse/issues/1905

fix: 'GenerationChunk' object has no attribute 'message'

---

langfuse/extract_model.py
tests/test_extract_model.py

This adds model parsing support for ChatBedrock from `langchain_aws`, since BedrockChat from has been deprecated.
```
The class `BedrockChat` was deprecated in LangChain 0.0.34 and will be removed in 0.3. An updated version of the class exists in the langchain-aws package and should be used instead. To use it run `pip install -U langchain-aws` and import as `from langchain_aws import ChatBedrock`
```

fix: add model support for langchain_aws

---

langfuse/callback/langchain.py
langfuse/client.py
langfuse/decorators/langfuse_decorator.py
langfuse/llama_index/llama_index.py
langfuse/openai.py
langfuse/task_manager.py
langfuse/utils/base_callback_handler.py
langfuse/utils/langfuse_singleton.py
tests/test_decorators.py
tests/test_langchain.py
tests/test_llama_index.py
tests/test_openai.py
tests/test_sdk_setup.py
tests/test_singleton.py
tests/test_task_manager.py

- Adds `enabled` switch that decides whether to send observability events to Langfuse (langfuse.trace/generation/event/score/span)
- Adds passing a custom HTTPX client for `llama-index` and `langchain` integrations

feat(core): adds httpx client and 'enabled'-switch for Langfuse

---

langfuse/client.py

When I set `LANGFUSE_FLUSH_AT=50`, I saw this error in logs:
```
File "/usr/local/lib/python3.11/site-packages/langfuse/task_manager.py", line 99, in _next
while len(items) < self._flush_at:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
```
This is because env vars are all strings:
```
$ FOO=50 python -c 'import os; print(type(os.getenv("FOO")))'
<class 'str'>
```
This fixes the code to instead get with a default value, and then cast to the expected type.

Fix incorrect types in client os.getenv calls

---

.github/workflows/ci.yml
tests/test_sdk_setup.py

- Fix long test runtimes due to misconfigured test
- add timeout to CI pipeline of 20 mins

fix: long test runtimes due to misconfigured test

---

langfuse/callback/langchain.py
langfuse/utils/base_callback_handler.py

- setNextSpan
- get_trace_id
- get_trace_url

docs: add deprecation warning to legacy callback handler methods

---

langfuse/openai.py
tests/test_openai.py

Hi
I added support to track the optional `seed` model parameter through the OpenAI integration.
_Screenshot from the trace generated by the unit test. You can also check the [public trace](https://cloud.langfuse.com/project/clqz1ivm90002q2hys8h23stv/traces/4a37f539-d7aa-41a1-a604-308e1edf7cd6?observation=93a6eb2c-1ea1-4850-85df-d1c61dc69f25)._

feat: add optional seed in openai model parameters

---

langfuse/serializer.py

When using langchain, an error was raised and generation could not be recorded
```
def test_langfuse():
from langfuse.callback import CallbackHandler
langfuse_handler = CallbackHandler(
public_key="pk-",
secret_key="sk-",
host="http://localhost:3000",
tags=[-2],
session_id=-2,
trace_name=-2,
user_id=-2,
debug=True
)
def chat():
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
chat_messages = [
("system", "You are a helpful assistant"),
("human", "Question: {{question}}")
]
prompt = ChatPromptTemplate.from_messages(
chat_messages,
template_format="mustache"
)
chain = prompt | ChatOpenAI(
model_name="qwen-72b",
openai_api_key="empty",
openai_api_base="http://localhost:8888/v1", …
```

fix: Fixed an error when the event serializer encountered Exception

---

langfuse/Sampler.py
langfuse/callback/langchain.py
langfuse/extract_model.py
langfuse/utils/__init__.py

Changes for supporting Watsonx.ai (https://python.langchain.com/v0.2/docs/integrations/llms/ibm_watsonx/)

Support for Watsonx ai model for langchain extension

---

langfuse/decorators/langfuse_decorator.py

Updated deprecated logging warning
langfuse_decorator.py:788: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
self._log.warn("No observation found in the current context")

Updated deprecated logging warning in langfuse_decorator.py

---

langfuse/decorators/langfuse_decorator.py
langfuse/task_manager.py

similar to #903, we should use warning across this repo instead of warn which is deprecated

chore: use logger.warning instead of logger.warn

---

langfuse/client.py
langfuse/prompt_cache.py
langfuse/version.py
pyproject.toml
tests/test_prompt.py
tests/test_prompt_atexit.py

uses threading logic similar to `task_manager`
Updated docs: https://github.com/langfuse/langfuse-docs/pull/787
In addition to tests, I also manually tested whether error handling prevents all sorts of errors to be captured, we have two layers of error handling to prevent any refresh exceptions causing issues in the main thread: (1) in get_prompt, (2) in PromptCacheRefreshConsumer.

feat(prompts): return stale prompt version and refresh prompt cache in background thread instead of waiting for the updated prompt

---

langfuse/callback/langchain.py

if an langchain retriever is without a chain, no parent run can be found:
```
retriever =  vectorstore.as_retriever(...)
retriever.invoke(input=query, config={"callbacks": [langfuse_handler]})
```
In this case, no exception is thrown but a new parent trace generated.
fixes https://github.com/langfuse/langfuse/issues/3223

fix(langchain) python langchain retriever - parent run not found 

---

langfuse/llama_index/llama_index.py

When I was using LangFuse in LlamaIndex, I encountered an exceptional situation. 
When the llm generates a `CBEventType.EXCEPTION`, the `_handle_span_events` function is executed. 
The events, it is a single-element list, causes an exception during execution. 
So I made modifications according to the writing method in other functions
Error line:
```
start_event, end_event = self.event_map[event_id]
```
Exception information:
```
ValueError: not enough values to unpack (expected 2, got 1)
```
CBEventType.EXCEPTION events example:
```
[
CallbackEvent(
event_type=<CBEventType.EXCEPTION: 'exception'>, 
payload={<EventPayload.EXCEPTION: 'exception'>: ResponseError('model "qwen2.5:72b" not found, try pulling it first')}, time=datetime.datetime(2024, 9, 23, 8, 34, 22, 529110, …
```

fix handle_span_events exception

---

langfuse/serializer.py
tests/test_serializer.py

This PR aims to fix the serialization of `None` to `"<not serializable object of type: NoneType>"` when langchain is not installed.
Related issue: https://github.com/langfuse/langfuse/issues/3570

fix(serializer): Fix None serialization without langchain installed
